imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }

parameters:
    locale: en
    project.name: WebHome
    app.code: CALD
    app.name: Calendar
    app.icon: glyphicon-calendar
    webhome_auth_url_api: "%webhome_auth_url%/api"

framework:
    esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        project_name: "%project.name%"
        app_name: "%app.name%"
        app_icon: "%app.icon%"
    form_themes: ['NdewezWebHomeCommonBundle:themes:back.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

hwi_oauth:
#    http_client:
#        timeout: 10
    firewall_names: [secured_area]
    resource_owners:
        webhome:
            type: oauth2
            client_id:           %client_id%
            client_secret:       %client_secret%
            authorization_url:   %webhome_auth_url%/oauth/v2/auth
            access_token_url:    %webhome_auth_url%/oauth/v2/token
            infos_url:           %webhome_auth_url%/api/user
            scope:               "read"
            user_response_class: Ndewez\WebHome\CommonBundle\Response\OAuthWebHomeUserResponse
            paths:
                identifier: id
                nickname:   username
                realname:   ["first_name", "last_name"]
                firstname:  first_name
                lastname:   last_name
                locale:     locale
                roles:      group.authorizations

ndewez_web_home_common:
    menu:
        session: false
        builder: app.menu.builder
    api_user_connected:
        session_key: user
        access_token_key:
            header: access-token
            get: access_token
#        required_paths:
#            - ^/api/v0/calendars
        optional_paths:
            - ^/api/v0

ndewez_web_home_auth_api:
    api_url: %webhome_auth_url_api%
    api_version: 0
